[theme]
base="dark"
primaryColor="#2dd247"
backgroundColor="rgb(48, 36, 92)"
#primaryColor="purple"
#backgroundColor="transparent"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="serif"
